server {
    listen 443 ssl;
    listen [::]:443 ssl;
    # [::] means all addresses. IPv6
    server_name rpadasia.42.fr;
    #which domain name this server block responds to

    ssl_certificate /etc/ssl/certs/cert.crt;
    #sent to the browser to prove the server's identity.
    ssl_certificate_key /etc/ssl/private/private.key;

    ssl_protocols TLSv1.3;
    #only allow TLSv1.3 connections

    index index.php;
    #entry point for wordpress when someone visits root of the site, will serve this
    root /var/www/html;
    #where NGINX looks for files

    location ~ [^/]\.php(/|$) {
        try_files $uri =404; #before passing to PHP, check if the file actually exists. $uri is the requested file path
        fastcgi_pass wordpress:9000; #forward the PHP request to the WordPress container on port 9000 via FastCGI
        include fastcgi_params; #things like request method, server name, query string
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;  tells PHP-FPM the full path of the PHP file to execute, will be "/var/www/html and /index.php"
    }
}

#The ~ means "use regex matching", so everything after it is a regular expression
#[^/] — match any single character that is not a forward slash
#match any character that isn't a slash
#- followed by .php
#- followed by either a slash or end of URL